### ISSUE TITLE
How is the end point name generated?

### ISSUE THREAD

**Issue by Karandev** [ARMmbed/java-coap#7] opened 2017-06-01 05:18 UTC
What is the algorithm used for generating end point name? Can we get the end point name from some REST API?

**Comment by szysas** [comment] 2017-06-01 07:57
There are REST API to create them: https://docs.mbed.com/docs/mbed-device-connector-web-interfaces/en/latest/api-reference/#create-a-certificate

**Comment by Karandev** [comment] 2017-06-01 08:51
Can we use android device serial number or IMEI number for domain ?

**Comment by szysas** [comment] 2017-06-01 08:59
No, that can not be used.

**Comment by Karandev** [comment] 2017-06-01 09:05
From where can we get this domain ID? Is there a seperate API for this?

**Comment by szysas** [comment] 2017-06-01 09:39
You can see it in https://connector.mbed.com/#credentials, it is in field `MBED_DOMAIN`.

**Comment by Karandev** [comment] 2017-06-02 04:07
We are getting a 402 error when passing valid domain id and public key generated programmatically. What could be the reason. We tried in Postman also.

**Comment by Karandev** [comment] 2017-06-02 04:22
Sorry it is 401 error

**Comment by szysas** [comment] 2017-06-02 05:51
What API are you trying to use?

**Comment by dkavinashgithub** [comment] 2017-06-02 09:58
below is the URL, payload and headers used to test the 'Create a certificate' API.
**URL:**
https://api.connector.mbed.com/api/cert

**Payload:**
{
"domain" : "ce12252f-5d74-4995-bf0b-57e07f30ccad"
"publickey": "-----BEGIN PUBLIC KEY-----a7e8cef3d24920dd230fde3cabd4caac4a2d2ce107172f03507dfa52296df29534e982e2fbfb724bcfbd1a6d65250f549d319397cd57fab22d1b6e44d3f259fe8ac5c7d274b5955100bdee54d16e7d92cc6dfbcbd932239dbba9cc2f1326ad3a4481a19176e7a17b4e43e205e7f3e1e14b6b5accb67174cbace414ac456768d9aba0502a9c7792bd0dc9d148eab02232a5cd7b5c2433b9a18c22823d1676193b9494f42ec97ec7526e46f72110b3b0f7b6ccd504d9ce13c54db8a5b265d54b63a0152f14ca080c2ce366e4947a3eddd50d9a05bb89a4ff1f702f8fe161b988dbecfdafa5b92e45207740b65d03e5d05c2f7762d6aee5fbf684894fd7cf652313-----END PUBLIC KEY-----"
}

**Headers:**
"Accept": "application/json"
"Content-Type":"application/json"
"access_key": "eXc90LwptTxe9BJAphoEpxvjytPxyELFECVI8fnFDl97wQ5cTYfiILQ8Cj66AOrzq23prUWuSMQQbzNgCx10Q75Pf9GwDhwPzidw"

**Comment by dkavinashgithub** [comment] 2017-06-02 10:21
sorry **URL** is https://connector.mbed.com/api/cert

**Comment by szysas** [comment] 2017-06-02 10:37
Please, do not copy paste access codes!

**Comment by dkavinashgithub** [comment] 2017-06-02 11:40
thanks szysas for resolving 401 issue. Now getting 400 Bad request error. suspecting it is issue with wrong payload. can you suggest where will be the probable root cause?

FYI we are using spongycastle java library to generate public key required for the payload. below is the code used to generate public key
`Security.insertProviderAt(new org.spongycastle.jce.provider.BouncyCastleProvider(), 1);
            final java.security.KeyPairGenerator rsaKeyPairGenerator = java.security.KeyPairGenerator.getInstance("RSA");
            rsaKeyPairGenerator.initialize(2048);
            final KeyPair rsaKeyPair =
                    rsaKeyPairGenerator.generateKeyPair();

            // Generate the key store de type JCEKS
            Provider[] ps = Security.getProviders();
            for (int i = 0; i < ps.length; i++)
                System.out.println("" + ps[i].getName());

            ks = KeyStore.getInstance("BKS");
            ks.load(null);

            final RSAPublicKey rsaPublicKey = (RSAPublicKey) rsaKeyPair.getPublic();
            String domain = "ce12252f-5d74-4995-bf0b-57e07f30ccad";
            StringBuilder szKey = new StringBuilder(rsaPublicKey.toString());`

**Comment by szysas** [comment] 2017-06-02 11:58
It seems that RSA key pair is not supported. You would need to create EC with key length 256 (recommended curve is secp256r1).

**Comment by Karandev** [comment] 2017-06-08 06:18
We obtained response from server for the certificates and generated a BKS keystore programmatically. We tried to do `startedCoapServer = coapServer.start();`, but an exception of Connection reset by peer was obtained.
Please help.

**Comment by szysas** [comment] 2017-06-08 11:23
Can you show logs?

**Comment by Karandev** [comment] 2017-06-08 12:05
`06-08 17:32:16.705 31594-32227/com.rpp.app W/System.err: javax.net.ssl.SSLHandshakeException: Connection closed by peer
06-08 17:32:16.707 31594-32227/com.rpp.app W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-08 17:32:16.708 31594-32227/com.rpp.app W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
06-08 17:32:16.714 31594-32227/com.rpp.app W/System.err:     at com.mbed.coap.transport.javassl.SSLSocketClientTransport.start(SSLSocketClientTransport.java:55)
06-08 17:32:16.716 31594-32227/com.rpp.app W/System.err:     at com.mbed.coap.server.CoapServer.start(CoapServer.java:166)
06-08 17:32:16.723 31594-32227/com.rpp.app W/System.err:     at com.rpp.activities.HomeActivity2$1$1.run(HomeActivity2.java:171)
06-08 17:32:16.724 31594-32227/com.rpp.app W/System.err:     at java.lang.Thread.run(Thread.java:761)
06-08 17:32:17.365 995-1180/? W/GCoreFlp: No location to return for getLastLocation()`

**Comment by szysas** [comment] 2017-06-08 12:17
This does not tell much, something wrong with certificate. Can you show your certificate? And structure of your keystore?

**Comment by Karandev** [comment] 2017-06-08 12:31
The code we are using are as follows:
`------------------------------------        
						//CERT.pem
                        writeToFileInPemFormat(jObjResponse.getString("device_certificate"), "CERT.pem");
                        //SERVER_CERT.pem
                        writeToFileInPemFormat(jObjResponse.getString("server_certificate"), "SERVER_CERT.pem");

                        //create Key Store
                        File root = android.os.Environment.getExternalStorageDirectory();

                        // byte[] keyBytes = parseDERFromPEM(fileToBytes(new File(root.getAbsolutePath() + "/download/" + "KEY.pem")), "-----BEGIN PRIVATE KEY-----", "-----END PRIVATE KEY-----");
                        byte[] certBytes = parseDERFromPEM(fileToBytes(new File(root.getAbsolutePath() + "/CERT.pem")), "-----BEGIN CERTIFICATE-----", "-----END CERTIFICATE-----");
                        byte[] serverCertBytes = parseDERFromPEM(fileToBytes(new File(root.getAbsolutePath() + "/SERVER_CERT.pem")), "-----BEGIN CERTIFICATE-----", "-----END CERTIFICATE-----");

                        //PemReader reader = new PemReader(new InputStreamReader(new ByteArrayInputStream(certBytes)));
                        X509Certificate cert = generateCertificateFromDER(certBytes);
                        X509Certificate servercert = generateCertificateFromDER(serverCertBytes);

                        CLI_KS = KeyStore.getInstance("BKS");
                        CLI_KS.load(null, "secret".toCharArray());
                        //CLI_KS.setCertificateEntry("device", cert);
                        CLI_KS.setCertificateEntry("server-ca", servercert);
                        CLI_KS.setKeyEntry("device", privatekey, "secret".toCharArray(), new Certificate[]{cert});

                        File file = new File(Environment.getExternalStorageDirectory().getAbsoluteFile(), "client.jks");
                        OutputStream fos = new FileOutputStream(file);
                        CLI_KS.store(fos, "secret".toCharArray());
						
--------------------------------------------
    private byte[] parseDERFromPEM(byte[] pem, String beginDelimiter, String endDelimiter) {
        String data = new String(pem);
        String[] tokens = data.split(beginDelimiter);
        tokens = tokens[1].split(endDelimiter);
        return Base64.decode(tokens[0], Base64.DEFAULT);
        // return DatatypeConverter.parseBase64Binary(tokens[0]);
    }
------------------------------------------------	
private static X509Certificate generateCertificateFromDER(byte[] certBytes) throws CertificateException {
        CertificateFactory factory = CertificateFactory.getInstance("X.509");
        return (X509Certificate) factory.generateCertificate(new ByteArrayInputStream(certBytes));
    }
-----------------------------------------------`

**Comment by szysas** [comment] 2017-06-08 12:39
can you copy paste certificate (toString result)

**Comment by Karandev** [comment] 2017-06-08 13:02
`--------------------------------------------
device certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1475269733 (0x57eed465)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, O=ARM, CN=mbed-connector-2018
                     Validity
                     Not Before: Jun  8 12:52:46 2017 GMT
                     Not After : Dec 31 06:00:00 2018 GMT
                     Subject: CN=ce12252f-5d74-4995-bf0b-57e07f30ccad/14b50910-ee51-4072-92e4-510368b35b2b, OU=ARM, O=mbed user, L=Oulu, ST=Oulu, C=FI
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 65 89 45 e8 2d 52 7d  d8 85 9d 73 1d 6a a7 33  |.e.E.-R}...s.j.3|
                     00000010  1b ab 12 63 5c d1 74 66  46 53 13 12 7f 10 57 13  |...c\.tfFS....W.|
                     00000020  35 12 5c 1b 43 44 2a 38  07 94 15 b9 c9 1b 07 c3  |5.\.CD*8........|
                     00000030  dc 10 40 2c 72 05 e2 40  4c d9 d5 99 44 bd 5f 0f  |..@,r..@L...D._.|
                     00000040  3d                                                |=|
                     Signature Algorithm: ecdsa-with-SHA256
                     30:44:02:20:4d:d6:20:33:c6:92:40:a8:11:bc:bb:d0:18:91:
                     0e:b7:42:a9:47:2a:90:7d:5f:19:c5:2e:72:51:2e:73:26:f2:
                     02:20:55:79:5d:97:81:14:15:c6:dd:e5:fc:11:17:97:e7:1b:
                     fc:0a:c0:d0:f8:64:b5:8d:35:43:e8:cd:1f:68:7d:6f
--------------------------------------------------------------------------																				  
server certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1430290642 (0x554080d2)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Validity
                     Not Before: Apr 29 06:57:48 2015 GMT
                     Not After : Apr 29 06:57:48 2018 GMT
                     Subject: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 bb 80 c8 b4 a4 d2 60  37 6b 08 05 47 99 b0 d9  |.......`7k..G...|
                     00000010  11 ed 87 8e ed 45 43 b8  e2 af d1 77 31 59 9c bb  |.....EC....w1Y..|
                     00000020  00 b1 dd 7c 12 cc 5d e4  b0 a9 71 3f 70 d2 db cd  |...|..]...q?p...|
                     00000030  7c 1b f8 c4 9c 46 c3 4c  1c 62 b3 c3 0d bf 3f ae  ||....F.L.b....?.|
                     00000040  3b                                                |;|
                     X509v3 extensions:
                     X509v3 Basic Constraints: 
                     CA:TRUE
                     Signature Algorithm: ecdsa-with-SHA256
                     30:45:02:21:00:f0:28:9c:40:24:c2:2c:65:26:2c:98:45:04:
                     16:a5:7b:64:31:96:b1:f9:59:44:89:2d:b4:d4:11:b4:3e:90:
                     33:02:20:61:d9:1b:03:37:12:ca:5b:07:f8:3b:b0:fa:25:ab:
                     06:05:87:fd:f9:92:f0:97:48:9a:46:34:e3:ca:d3:be:2b
-----------------------------------------------------------------------------------`

**Comment by Karandev** [comment] 2017-06-08 13:02
--------------------------------------------
device certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1475269733 (0x57eed465)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, O=ARM, CN=mbed-connector-2018
                     Validity
                     Not Before: Jun  8 12:52:46 2017 GMT
                     Not After : Dec 31 06:00:00 2018 GMT
                     Subject: CN=ce12252f-5d74-4995-bf0b-57e07f30ccad/14b50910-ee51-4072-92e4-510368b35b2b, OU=ARM, O=mbed user, L=Oulu, ST=Oulu, C=FI
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 65 89 45 e8 2d 52 7d  d8 85 9d 73 1d 6a a7 33  |.e.E.-R}...s.j.3|
                     00000010  1b ab 12 63 5c d1 74 66  46 53 13 12 7f 10 57 13  |...c\.tfFS....W.|
                     00000020  35 12 5c 1b 43 44 2a 38  07 94 15 b9 c9 1b 07 c3  |5.\.CD*8........|
                     00000030  dc 10 40 2c 72 05 e2 40  4c d9 d5 99 44 bd 5f 0f  |..@,r..@L...D._.|
                     00000040  3d                                                |=|
                     Signature Algorithm: ecdsa-with-SHA256
                     30:44:02:20:4d:d6:20:33:c6:92:40:a8:11:bc:bb:d0:18:91:
                     0e:b7:42:a9:47:2a:90:7d:5f:19:c5:2e:72:51:2e:73:26:f2:
                     02:20:55:79:5d:97:81:14:15:c6:dd:e5:fc:11:17:97:e7:1b:
                     fc:0a:c0:d0:f8:64:b5:8d:35:43:e8:cd:1f:68:7d:6f
--------------------------------------------------------------------------																				  
server certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1430290642 (0x554080d2)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Validity
                     Not Before: Apr 29 06:57:48 2015 GMT
                     Not After : Apr 29 06:57:48 2018 GMT
                     Subject: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 bb 80 c8 b4 a4 d2 60  37 6b 08 05 47 99 b0 d9  |.......`7k..G...|
                     00000010  11 ed 87 8e ed 45 43 b8  e2 af d1 77 31 59 9c bb  |.....EC....w1Y..|
                     00000020  00 b1 dd 7c 12 cc 5d e4  b0 a9 71 3f 70 d2 db cd  |...|..]...q?p...|
                     00000030  7c 1b f8 c4 9c 46 c3 4c  1c 62 b3 c3 0d bf 3f ae  ||....F.L.b....?.|
                     00000040  3b                                                |;|
                     X509v3 extensions:
                     X509v3 Basic Constraints: 
                     CA:TRUE
                     Signature Algorithm: ecdsa-with-SHA256
                     30:45:02:21:00:f0:28:9c:40:24:c2:2c:65:26:2c:98:45:04:
                     16:a5:7b:64:31:96:b1:f9:59:44:89:2d:b4:d4:11:b4:3e:90:
                     33:02:20:61:d9:1b:03:37:12:ca:5b:07:f8:3b:b0:fa:25:ab:
                     06:05:87:fd:f9:92:f0:97:48:9a:46:34:e3:ca:d3:be:2b
-----------------------------------------------------------------------------------

**Comment by Karandev** [comment] 2017-06-08 13:04
`--------------------------------------------
device certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1475269733 (0x57eed465)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, O=ARM, CN=mbed-connector-2018
                     Validity
                     Not Before: Jun  8 12:52:46 2017 GMT
                     Not After : Dec 31 06:00:00 2018 GMT
                     Subject: CN=ce12252f-5d74-4995-bf0b-57e07f30ccad/14b50910-ee51-4072-92e4-510368b35b2b, OU=ARM, O=mbed user, L=Oulu, ST=Oulu, C=FI
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 65 89 45 e8 2d 52 7d  d8 85 9d 73 1d 6a a7 33  |.e.E.-R}...s.j.3|
                     00000010  1b ab 12 63 5c d1 74 66  46 53 13 12 7f 10 57 13  |...c\.tfFS....W.|
                     00000020  35 12 5c 1b 43 44 2a 38  07 94 15 b9 c9 1b 07 c3  |5.\.CD*8........|
                     00000030  dc 10 40 2c 72 05 e2 40  4c d9 d5 99 44 bd 5f 0f  |..@,r..@L...D._.|
                     00000040  3d                                                |=|
                     Signature Algorithm: ecdsa-with-SHA256
                     30:44:02:20:4d:d6:20:33:c6:92:40:a8:11:bc:bb:d0:18:91:
                     0e:b7:42:a9:47:2a:90:7d:5f:19:c5:2e:72:51:2e:73:26:f2:
                     02:20:55:79:5d:97:81:14:15:c6:dd:e5:fc:11:17:97:e7:1b:
                     fc:0a:c0:d0:f8:64:b5:8d:35:43:e8:cd:1f:68:7d:6f
--------------------------------------------------------------------------																				  
server certificate:: Certificate:
                     Data:
                     Version: 3 (0x2)
                     Serial Number: 1430290642 (0x554080d2)
                     Signature Algorithm: ecdsa-with-SHA256
                     Issuer: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Validity
                     Not Before: Apr 29 06:57:48 2015 GMT
                     Not After : Apr 29 06:57:48 2018 GMT
                     Subject: C=FI, L=Oulu, O=ARM, OU=IoT, CN=ARM mbed
                     Subject Public Key Info:
                     Public Key Algorithm: id-ecPublicKey
                     Public-Key: (256 bit)
                     00000000  04 bb 80 c8 b4 a4 d2 60  37 6b 08 05 47 99 b0 d9  |.......`7k..G...|
                     00000010  11 ed 87 8e ed 45 43 b8  e2 af d1 77 31 59 9c bb  |.....EC....w1Y..|
                     00000020  00 b1 dd 7c 12 cc 5d e4  b0 a9 71 3f 70 d2 db cd  |...|..]...q?p...|
                     00000030  7c 1b f8 c4 9c 46 c3 4c  1c 62 b3 c3 0d bf 3f ae  ||....F.L.b....?.|
                     00000040  3b                                                |;|
                     X509v3 extensions:
                     X509v3 Basic Constraints: 
                     CA:TRUE
                     Signature Algorithm: ecdsa-with-SHA256
                     30:45:02:21:00:f0:28:9c:40:24:c2:2c:65:26:2c:98:45:04:
                     16:a5:7b:64:31:96:b1:f9:59:44:89:2d:b4:d4:11:b4:3e:90:
                     33:02:20:61:d9:1b:03:37:12:ca:5b:07:f8:3b:b0:fa:25:ab:
                     06:05:87:fd:f9:92:f0:97:48:9a:46:34:e3:ca:d3:be:2b
-----------------------------------------------------------------------------------`

**Comment by Karandev** [comment] 2017-06-08 13:05
[certs.txt](https://github.com/ARMmbed/java-coap/files/1061064/certs.txt)

**Closed** 2018-03-21 12:05 UTC
